import type { TableRules } from "@/types/user";

export const DEFAULT_RULES: TableRules = {
  deckCount: 6,
  dealerStand: "s17",
  blackjackPayout: "3:2",
  doubleAfterSplit: true,
  surrender: "none",
  doubleRestriction: "any",
  resplitAces: false,
  hitSplitAces: false,
  maxSplits: 3,
  maxPlayableHands: 5,
  minBet: 5,
  maxBet: 1000,
  betUnit: 5,
};

export const PRESET_RULES: Record<string, TableRules> = {
  default: DEFAULT_RULES,
  "vegas-strip": {
    deckCount: 4,
    dealerStand: "s17",
    blackjackPayout: "3:2",
    doubleAfterSplit: true,
    surrender: "late",
    doubleRestriction: "any",
    resplitAces: false,
    hitSplitAces: false,
    maxSplits: 3,
    maxPlayableHands: 5,
    minBet: 25,
    maxBet: 5000,
    betUnit: 25,
  },
  "atlantic-city": {
    deckCount: 8,
    dealerStand: "s17",
    blackjackPayout: "3:2",
    doubleAfterSplit: true,
    surrender: "late",
    doubleRestriction: "any",
    resplitAces: false,
    hitSplitAces: false,
    maxSplits: 3,
    maxPlayableHands: 5,
    minBet: 10,
    maxBet: 2000,
    betUnit: 10,
  },
  "single-deck": {
    deckCount: 1,
    dealerStand: "h17",
    blackjackPayout: "3:2",
    doubleAfterSplit: false,
    surrender: "none",
    doubleRestriction: "10-11",
    resplitAces: false,
    hitSplitAces: false,
    maxSplits: 3,
    maxPlayableHands: 5,
    minBet: 5,
    maxBet: 500,
    betUnit: 5,
  },
  liberal: {
    deckCount: 4,
    dealerStand: "s17",
    blackjackPayout: "3:2",
    doubleAfterSplit: true,
    surrender: "late",
    doubleRestriction: "any",
    resplitAces: true,
    hitSplitAces: false,
    maxSplits: 3,
    maxPlayableHands: 5,
    minBet: 5,
    maxBet: 1000,
    betUnit: 5,
  },
};
