import type { TableRules } from "./user";

export interface RulesPreset {
  id: string;
  name: string;
  description: string;
  rules: TableRules;
  isBuiltIn: boolean; // Built-in presets cannot be deleted
  createdAt?: string;
}

export const BUILT_IN_PRESETS: RulesPreset[] = [
  {
    id: "standard",
    name: "Standard ($5 Table)",
    description: "6 decks, S17, 3:2 BJ, DAS - Most common casino rules",
    isBuiltIn: true,
    rules: {
      deckCount: 6,
      dealerStand: "s17",
      blackjackPayout: "3:2",
      doubleAfterSplit: true,
      surrender: "none",
      doubleRestriction: "any",
      resplitAces: false,
      hitSplitAces: false,
      maxSplits: 3,
      maxPlayableHands: 5,
      minBet: 5,
      maxBet: 1000,
      betUnit: 5,
    },
  },
  {
    id: "vegas-strip",
    name: "Vegas Strip ($25 Table)",
    description: "4 decks, S17, 3:2 BJ, Late Surrender - Player-friendly",
    isBuiltIn: true,
    rules: {
      deckCount: 4,
      dealerStand: "s17",
      blackjackPayout: "3:2",
      doubleAfterSplit: true,
      surrender: "late",
      doubleRestriction: "any",
      resplitAces: false,
      hitSplitAces: false,
      maxSplits: 3,
      maxPlayableHands: 5,
      minBet: 25,
      maxBet: 5000,
      betUnit: 25,
    },
  },
  {
    id: "atlantic-city",
    name: "Atlantic City ($10 Table)",
    description: "8 decks, S17, 3:2 BJ, Late Surrender",
    isBuiltIn: true,
    rules: {
      deckCount: 8,
      dealerStand: "s17",
      blackjackPayout: "3:2",
      doubleAfterSplit: true,
      surrender: "late",
      doubleRestriction: "any",
      resplitAces: false,
      hitSplitAces: false,
      maxSplits: 3,
      maxPlayableHands: 5,
      minBet: 10,
      maxBet: 2000,
      betUnit: 10,
    },
  },
  {
    id: "single-deck",
    name: "Single Deck ($5 Table)",
    description: "1 deck, H17, Restricted double - Old school Vegas",
    isBuiltIn: true,
    rules: {
      deckCount: 1,
      dealerStand: "h17",
      blackjackPayout: "3:2",
      doubleAfterSplit: false,
      surrender: "none",
      doubleRestriction: "10-11",
      resplitAces: false,
      hitSplitAces: false,
      maxSplits: 3,
      maxPlayableHands: 5,
      minBet: 5,
      maxBet: 500,
      betUnit: 5,
    },
  },
  {
    id: "high-roller",
    name: "High Roller ($100 Table)",
    description: "6 decks, S17, 3:2 BJ, All options - Premium experience",
    isBuiltIn: true,
    rules: {
      deckCount: 6,
      dealerStand: "s17",
      blackjackPayout: "3:2",
      doubleAfterSplit: true,
      surrender: "late",
      doubleRestriction: "any",
      resplitAces: true,
      hitSplitAces: false,
      maxSplits: 4,
      maxPlayableHands: 5,
      minBet: 100,
      maxBet: 100000,
      betUnit: 100,
    },
  },
  {
    id: "low-limit",
    name: "Low Limit ($1 Table)",
    description: "6 decks, S17, 3:2 BJ - Perfect for practice",
    isBuiltIn: true,
    rules: {
      deckCount: 6,
      dealerStand: "s17",
      blackjackPayout: "3:2",
      doubleAfterSplit: true,
      surrender: "none",
      doubleRestriction: "any",
      resplitAces: false,
      hitSplitAces: false,
      maxSplits: 3,
      maxPlayableHands: 5,
      minBet: 1,
      maxBet: 100,
      betUnit: 1,
    },
  },
];
